# Generated by Django 3.0.4 on 2020-04-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nome', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=5, max_digits=7)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('med', 'Medicamento'), ('equip', 'Equipamento Veterinário'), ('limp', 'Material de Limpeza')], max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('quant_un', models.DecimalField(decimal_places=2, max_digits=5)),
                ('un_medida', models.CharField(choices=[('l', 'l'), ('ml', 'ml'), ('g', 'g'), ('mg', 'mg')], max_length=3)),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Saida_Leite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('destino', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Femea',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teste.Animal')),
                ('inicLact', models.DateField(blank=True, null=True)),
                ('fimLact', models.DateField(blank=True, null=True)),
            ],
            bases=('teste.animal',),
        ),
        migrations.CreateModel(
            name='Macho',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teste.Animal')),
                ('inicRepr', models.DateField(blank=True, null=True)),
                ('fimRepr', models.DateField(blank=True, null=True)),
            ],
            bases=('teste.animal',),
        ),
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Gasto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Acessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(choices=[('adm', 'Administrador'), ('cord', 'Cordenador'), ('bols', 'Bolsista'), ('vist', 'Visitante')], max_length=15)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Secacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('leite', models.CharField(choices=[('n', 'NÃO MAIS'), ('p', 'POUCO LEITE'), ('m', 'MUITO LEITE')], max_length=30)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.Femea')),
            ],
        ),
        migrations.CreateModel(
            name='Produc_leite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('femea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Femea')),
            ],
        ),
        migrations.CreateModel(
            name='Nascimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obito', models.BooleanField()),
                ('filhote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Animal')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matriz', to='teste.Femea')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pai', to='teste.Macho')),
            ],
        ),
        migrations.CreateModel(
            name='Gravidez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Femea')),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('femea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.Femea')),
                ('macho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.Macho')),
            ],
        ),
    ]
