# Generated by Django 3.0.4 on 2020-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobertura',
            name='fim',
        ),
        migrations.AddField(
            model_name='cobertura',
            name='inicio2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gravidez',
            name='inicio2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
