# Generated by Django 3.0.4 on 2020-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20200416_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(default='Bovino', max_length=30),
        ),
    ]
