# Generated by Django 3.0.4 on 2020-08-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_auto_20200514_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macho',
            name='animal_ptr',
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='femea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='femea', to='teste.Animal'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='macho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='macho', to='teste.Animal'),
        ),
        migrations.AlterField(
            model_name='gravidez',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Animal'),
        ),
        migrations.AlterField(
            model_name='nascimento',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matriz', to='teste.Animal'),
        ),
        migrations.AlterField(
            model_name='nascimento',
            name='pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pai', to='teste.Animal'),
        ),
        migrations.AlterField(
            model_name='produc_leite',
            name='femea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Animal'),
        ),
        migrations.AlterField(
            model_name='secacao',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.Animal'),
        ),
        migrations.DeleteModel(
            name='Femea',
        ),
        migrations.DeleteModel(
            name='Macho',
        ),
    ]
