# Generated by Django 3.0.4 on 2020-09-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_auto_20200802_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aquisicao',
        ),
    ]
